<a href="https://colab.research.google.com/github/brayan-lliuya-2024/PC2-Brayan_Lliuya/blob/main/LimpiezaDeDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd


#Automcompletar rápido
%config IPCompleter.greedy=True
#Desactivar la notación científica
pd.options.display.float_format = '{:.3f}'.format

#Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!pip install html5lib lxml beautifulsoup4

Requirement already satisfied: html5lib in /usr/local/lib/python3.10/dist-packages (1.1)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (4.9.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (4.12.3)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.10/dist-packages (from html5lib) (1.16.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from html5lib) (0.5.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4) (2.6)

In [3]:
df = pd.read_csv("/content/drive/My Drive/Control2/HDI.csv", encoding='ISO-8859-1')

In [4]:
df.head(5)

,ï»¿,Unnamed: 1,Unnamed: 2,Unnamed: 3,SDG3,Unnamed: 5,SDG4.3,Unnamed: 7,SDG4.4,Unnamed: 9,SDG8.5,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank
2,HDI rank,Country,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN
3,NaN,NaN,2021,NaN,2021,NaN,2021,a,2021,a,2021,NaN,2021,b,2020
4,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.tail(6)

,ï»¿,Unnamed: 1,Unnamed: 2,Unnamed: 3,SDG3,Unnamed: 5,SDG4.3,Unnamed: 7,SDG4.4,Unnamed: 9,SDG8.5,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
268,NaN,Columns 1 and 7: HDRO calculations based on da...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
271,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_cleaned = pd.read_csv("/content/drive/My Drive/Control2/HDI.csv", skiprows=4)

In [7]:
df_cleaned = df_cleaned.drop(columns=['Unnamed: 5', 'Unnamed: 7', 'Unnamed: 9', 'Unnamed: 11', 'Unnamed: 13', 'Unnamed: 14'], errors='ignore')

In [8]:
df_cleaned.head()

,Unnamed: 0,Unnamed: 1,2021,Unnamed: 3,2021.1,2021.2,a,2021.3,a.1,2021.4,2021.5,b,2020
0,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.000,Switzerland,0.962,NaN,84.000,16.5,NaN,13.9,NaN,"66,933",5,NaN,3
2,2.000,Norway,0.961,NaN,83.200,18.2,c,13,NaN,"64,660",6,NaN,1
3,3.000,Iceland,0.959,NaN,82.700,19.2,c,13.8,NaN,"55,782",11,NaN,2
4,4.000,"Hong Kong, China (SAR)",0.952,NaN,85.500,17.3,NaN,12.2,NaN,"62,607",6,NaN,4

In [9]:
print(len(df_cleaned.columns))  # Esto te mostrará el número de columnas actuales

13

In [10]:
df_cleaned = pd.read_csv("/content/drive/My Drive/Control2/HDI.csv", skiprows=2)

In [11]:
df_cleaned.head()

,Unnamed: 0,Unnamed: 1,Human Development Index (HDI),Unnamed: 3,Life expectancy at birth,Unnamed: 5,Expected years of schooling,Unnamed: 7,Mean years of schooling,Unnamed: 9,Gross national income (GNI) per capita,Unnamed: 11,GNI per capita rank minus HDI rank,Unnamed: 13,HDI rank
0,HDI rank,Country,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN
1,NaN,NaN,2021,NaN,2021,NaN,2021,a,2021,a,2021,NaN,2021,b,2020
2,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Switzerland,0.962,NaN,84,NaN,16.5,NaN,13.9,NaN,"66,933",NaN,5,NaN,3
4,2,Norway,0.961,NaN,83.2,NaN,18.2,c,13,NaN,"64,660",NaN,6,NaN,1

In [12]:
df_cleaned = df_cleaned.rename(columns={'Unnamed: 0': 'HDI rank', 'Unnamed: 1': 'Country'})

In [13]:
df_cleaned = df_cleaned.iloc[:, :-1]

In [14]:
df_cleaned.head()

,HDI rank,Country,Human Development Index (HDI),Unnamed: 3,Life expectancy at birth,Unnamed: 5,Expected years of schooling,Unnamed: 7,Mean years of schooling,Unnamed: 9,Gross national income (GNI) per capita,Unnamed: 11,GNI per capita rank minus HDI rank,Unnamed: 13
0,HDI rank,Country,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN
1,NaN,NaN,2021,NaN,2021,NaN,2021,a,2021,a,2021,NaN,2021,b
2,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Switzerland,0.962,NaN,84,NaN,16.5,NaN,13.9,NaN,"66,933",NaN,5,NaN
4,2,Norway,0.961,NaN,83.2,NaN,18.2,c,13,NaN,"64,660",NaN,6,NaN

In [15]:
df_cleaned = df_cleaned.iloc[2:]

In [16]:
columns_to_drop = ['Unnamed: 3', 'Unnamed: 5', 'Unnamed: 7', 'Unnamed: 9', 'Unnamed: 11', 'Unnamed: 13']
df_cleaned = df_cleaned.drop(columns=columns_to_drop, errors='ignore')

In [17]:
df_cleaned.head()

,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank
2,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Switzerland,0.962,84,16.5,13.9,"66,933",5
4,2,Norway,0.961,83.2,18.2,13,"64,660",6
5,3,Iceland,0.959,82.7,19.2,13.8,"55,782",11
6,4,"Hong Kong, China (SAR)",0.952,85.5,17.3,12.2,"62,607",6

In [18]:
df_cleaned = df_cleaned.reset_index(drop=True)

In [19]:
df_cleaned.head()

,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank
0,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Switzerland,0.962,84,16.5,13.9,"66,933",5
2,2,Norway,0.961,83.2,18.2,13,"64,660",6
3,3,Iceland,0.959,82.7,19.2,13.8,"55,782",11
4,4,"Hong Kong, China (SAR)",0.952,85.5,17.3,12.2,"62,607",6

In [20]:
df_cleaned.info();

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   HDI rank                                191 non-null    object
 1   Country                                 260 non-null    object
 2   Human Development Index (HDI)           210 non-null    object
 3   Life expectancy at birth                210 non-null    object
 4   Expected years of schooling             210 non-null    object
 5   Mean years of schooling                 210 non-null    object
 6   Gross national income (GNI) per capita  210 non-null    object
 7   GNI per capita rank minus HDI rank      210 non-null    object
dtypes: object(8)
memory usage: 17.0+ KB

In [21]:
df_cleaned.dtypes

HDI rank                                  object
Country                                   object
Human Development Index (HDI)             object
Life expectancy at birth                  object
Expected years of schooling               object
Mean years of schooling                   object
Gross national income (GNI) per capita    object
GNI per capita rank minus HDI rank        object
dtype: object

In [22]:
df_cleaned = df_cleaned.drop(columns=['HDI rank'])

In [23]:
df_cleaned['Country'] = df_cleaned['Country'].str.strip()

In [24]:
df_cleaned.dtypes

Country                                   object
Human Development Index (HDI)             object
Life expectancy at birth                  object
Expected years of schooling               object
Mean years of schooling                   object
Gross national income (GNI) per capita    object
GNI per capita rank minus HDI rank        object
dtype: object

In [25]:
df_cleaned.replace({'—': 0, '..': 0}, inplace=True)

In [26]:
df_cleaned['Gross national income (GNI) per capita'] = df_cleaned['Gross national income (GNI) per capita'].str.replace(',', '').astype(float)

In [27]:
df_cleaned.head()

,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank
0,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN
1,Switzerland,0.962,84,16.5,13.9,66933.000,5
2,Norway,0.961,83.2,18.2,13,64660.000,6
3,Iceland,0.959,82.7,19.2,13.8,55782.000,11
4,"Hong Kong, China (SAR)",0.952,85.5,17.3,12.2,62607.000,6

In [28]:
df_cleaned.dtypes

Country                                    object
Human Development Index (HDI)              object
Life expectancy at birth                   object
Expected years of schooling                object
Mean years of schooling                    object
Gross national income (GNI) per capita    float64
GNI per capita rank minus HDI rank         object
dtype: object

In [29]:
df_cleaned["Life expectancy at birth"] = df_cleaned["Life expectancy at birth"].astype(float)
df_cleaned["Expected years of schooling"] = df_cleaned["Expected years of schooling"].astype(float)
df_cleaned["Mean years of schooling"] = df_cleaned["Mean years of schooling"].astype(float)
df_cleaned["GNI per capita rank minus HDI rank"] = df_cleaned["GNI per capita rank minus HDI rank"].astype(float)

In [30]:
df_cleaned.dtypes

Country                                    object
Human Development Index (HDI)              object
Life expectancy at birth                  float64
Expected years of schooling               float64
Mean years of schooling                   float64
Gross national income (GNI) per capita    float64
GNI per capita rank minus HDI rank        float64
dtype: object

In [31]:
df_cleaned.columns = df_cleaned.columns.str.strip()

In [32]:
df_cleaned["Human Development Index (HDI)"] = df_cleaned["Human Development Index (HDI)"].astype(float)

In [33]:
df_cleaned.dtypes

Country                                    object
Human Development Index (HDI)             float64
Life expectancy at birth                  float64
Expected years of schooling               float64
Mean years of schooling                   float64
Gross national income (GNI) per capita    float64
GNI per capita rank minus HDI rank        float64
dtype: object

In [34]:
df_cleaned.head()

,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank
0,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN
1,Switzerland,0.962,84.000,16.500,13.900,66933.000,5.000
2,Norway,0.961,83.200,18.200,13.000,64660.000,6.000
3,Iceland,0.959,82.700,19.200,13.800,55782.000,11.000
4,"Hong Kong, China (SAR)",0.952,85.500,17.300,12.200,62607.000,6.000

In [35]:
import pandas as pd
from google.colab import drive

# Monta Google Drive
drive.mount('/content/drive')

# Guarda el DataFrame en un archivo CSV en tu Google Drive
df_cleaned.to_csv('/content/drive/My Drive/Control2/df_cleaned.csv', index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).